---
dbservers:
  hosts:
    postgres-azure:
      ansible_host: 52.236.122.57
      ansible_user: ds-azure
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

appservers:
    hosts:
      appserver-vm:
        ansible_host: 4.210.73.93
        ansible_user: azure-spring
        ansible_ssh_private_key_file: ~/.ssh/id_rsa

docker:
    hosts:
      appserver-vm:
        ansible_host: 20.123.91.17
        ansible_user: azureuser
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
