---
# Jenkins Server (CI/CD)
dbservers:
  hosts:
    jenkins-vm:
      ansible_host: jenkins-vm

# Docker
docker:
    hosts:
      docker-vm:
        ansible_host: docker-vm

# Spring on VM
appserver:
  hosts:
    app-server-vm:
      ansible_host: app-server-vm

# DB on VM
dbserver:
  hosts:
    db-server-vm:
      ansible_host: db-server-vm
