---
# Jenkins Server (CI/CD)
dbservers:
  hosts:
    postgres-azure:
      ansible_host: 52.236.122.57
      ansible_user: ds-azure
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

# microk8s
appservers:
    hosts:
      appserver-vm:  
        ansible_host: 4.210.73.93
        ansible_user: azure-spring
        ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Docker
docker:
    hosts:
      docker-vm:
        ansible_host: docker-vm

# Spring on VM
appserver:
  hosts:
    app-server-vm:
      ansible_host: app-server-vm

# DB on VM
dbserver:
  hosts:
    db-server-vm:
      ansible_host: db-server-vm
