---
# Jenkins Server (CI/CD)
dbservers:
  hosts:
    postgres-azure:
      ansible_host: 52.236.122.57
      ansible_user: ds-azure
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

# microk8s
appservers:
    hosts:
      appserver-vm:  
        ansible_host: 4.210.73.93
        ansible_user: azure-spring
        ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Docker
docker:
    hosts:
      appserver-docker:
        ansible_host: 20.123.91.17
        ansible_user: azureuser
        ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Spring on VM
appserver-vagrant:
  hosts:
    vagrant-appserver:
      ansible_host: 192.168.56.101
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/id_devops

# DB on VM
dbservers-vagrant:
  hosts:
    vagrant-dbserver:
      ansible_host: 192.168.56.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/id_devops
