- name: Drop PostgreSQL database from container host
  hosts: appserver-docker
  become: yes
  vars:
    db_name: colab
    db_user: myapp_user
    db_password: myapp_password
    db_host: localhost
    db_port: 5432

  tasks:
    - name: Install PostgreSQL client
      apt:
        name: postgresql-client
        state: present

    - name: Terminate active connections
      community.postgresql.postgresql_query:
        db: postgres
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        query: >
          SELECT pg_terminate_backend(pid)
          FROM pg_stat_activity
          WHERE datname = '{{ db_name }}'
          AND pid <> pg_backend_pid();

    - name: Drop the database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: absent
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ appdir }}"
        state: absent
