---
  - name: Update Kubernetes Deployment Image
    hosts: localhost # Επειδή θα τρέξει στον jenkins server
    gather_facts: no
    vars:
      namespace: default
      deployment_name: spring-deployment
      container_name: spring
      #new_image: "ghcr.io/karatziask/ds-project:latest"

    tasks:
      - name: Patch deployment image
        kubernetes.core.k8s_json_patch:
          kubeconfig: "/var/lib/jenkins/.kube/devops-microk8s"
          kind: Deployment
          namespace: "{{ namespace }}"
          name: "{{ deployment_name }}"
          patch:
            - op: replace
              path: /spec/template/spec/containers/0/image
              value: "{{ new_image }}"


      - name: Wait for rollout to complete
        command: kubectl rollout status deployment/{{ deployment_name }} -n {{ namespace }} --timeout=360s
        register: rollout_result
        environment:
          KUBECONFIG: "/var/lib/jenkins/.kube/devops-microk8s"
        failed_when: "'successfully rolled out' not in rollout_result.stdout"
        changed_when: false

      - name: Get pods in deployment
        kubernetes.core.k8s_info:
          kubeconfig: "/var/lib/jenkins/.kube/devops-microk8s"
          kind: Pod
          namespace: "{{ namespace }}"
          label_selectors:
            - "app={{ deployment_name }}"
        register: pod_list

      - name: Ensure all pods use the correct image
        fail:
          msg: "One or more pods do not have the updated image {{ new_image }}"
        when: >
          pod_list.resources | selectattr('status.phase', 'equalto', 'Running') |
          selectattr('spec.containers', 'defined') |
          reject('containers_all_use_image', new_image) | list | length > 0