---
- hosts: postgres-azure
  become: yes
  become_user: root
  tasks:

    # Κλείνει όλες τις ενεργές συνδέσεις για την επιλεγμένη βάση δεδομένων
    - name: Terminate active sessions on the database
      postgresql_query:
        db: "{{ db.name }}"
        query: "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '{{ db.name }}' AND pid <> pg_backend_pid();"
      become: yes
      become_user: postgres

    # Διαγράφει τη βάση δεδομένων αν υπάρχει
    - name: Drop database if exists
      postgresql_db:
        name: "{{ db.name }}"
        state: absent
      become: yes
      become_user: postgres
