pipeline {

agent any

// environment {
//         DOCKER_TOKEN=credentials('docker-push-secret')
//         DOCKER_USER='Kyriakos'
//         DOCKER_SERVER='ghcr.io'
//         DOCKER_PREFIX='ghcr.io/karatziask/ds-project'
//     }


stages {


    stage('Test') {
        steps {
            sh '''
                pwd
                echo "Start testing"
                ./mvnw test
            '''
        }
    }

}

}