pipeline {

agent any

environment {
        DOCKER_TOKEN=credentials('docker-push-secret')
        DOCKER_USER='Kyriakos'
        DOCKER_SERVER='ghcr.io'
        DOCKER_PREFIX='ghcr.io/karatziask/ds-project'
    }


stages {


    stage('Tests Spring-Boot') {
        steps {
            sh '''
                pwd
                cd ..
                cd DS-project
                echo "Start testing"
                ./mvnw test
            '''
        }
    }

    // stage('Docker build and push') {
    //         steps {
    //             dir('playbooks-docker'){
    //             sh '''
    //                 HEAD_COMMIT=$(git rev-parse --short HEAD)   
    //                 TAG=$HEAD_COMMIT-$BUILD_ID
    //                 docker build --rm -t $DOCKER_PREFIX:$TAG -t $DOCKER_PREFIX:latest -f nonroot-multistage.Dockerfile .
    //             '''

    //             sh '''
    //                 echo $DOCKER_TOKEN | docker login $DOCKER_SERVER -u $DOCKER_USER --password-stdin
    //                 docker push $DOCKER_PREFIX --all-tags
    //             '''
    //             }
    //         }
    //     }

stage('Docker build and push') {
  steps {
    sh '''
      docker build \
        -f playbooks-kubernetes/nonroot-multistage.Dockerfile \
        -t $DOCKER_PREFIX:${GIT_COMMIT}-${BUILD_NUMBER} \
        -t $DOCKER_PREFIX:latest \
        .
      echo $DOCKER_TOKEN | docker login $DOCKER_SERVER -u $DOCKER_USER --password-stdin
      docker push $DOCKER_PREFIX --all-tags
    '''
  }
}

}

}